[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server/api/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@node-rs/bcrypt", "@node-rs/helper"]
  included_files = ["app/api/**/*"]

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NEXT_TELEMETRY_DISABLED = "1"
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_PATHS = ".next/**/*"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false 