export function getOpportunities() {
  return [
    {
      id: 1,
      title: "Teach English to Refugees",
      organization: "Refugee Support Network",
      description: "Help refugees improve their English language skills through weekly classes.",
      category: "Education",
      commitment: "2 hours/week",
      distance: 2.0,
      latitude: 40.7128,
      longitude: -74.0060,
      image: "/images/teach-english.jpg",
      date: "2025-02-03T15:00:00Z", // Monday afternoon
      time: "3:00 PM",
      day: "Monday",
      recurring: true,
      spots_available: 5,
    },
    {
      id: 2,
      title: "Community Garden Volunteer",
      organization: "Green City Initiative",
      description: "Assist in maintaining and growing produce in our community garden.",
      category: "Environment",
      commitment: "Flexible",
      distance: 1.1,
      latitude: 40.7282,
      longitude: -73.9942,
      image: "/images/community-garden.jpg",
      date: "2025-02-08T10:00:00Z", // Saturday morning
      time: "10:00 AM",
      day: "Saturday",
      recurring: true,
      spots_available: 10,
    },
    {
      id: 3,
      title: "Elder Care Companion",
      organization: "Silver Years Foundation",
      description: "Provide companionship and assistance to elderly individuals in their homes.",
      category: "Health",
      commitment: "3 hours/week",
      distance: 2.8,
      latitude: 40.7589,
      longitude: -73.9851,
      image: "/images/elder-care.jpg",
      date: "2025-02-05T14:00:00Z", // Wednesday afternoon
      time: "2:00 PM",
      day: "Wednesday",
      recurring: true,
      spots_available: 3,
    },
    {
      id: 4,
      title: "Food Bank Distribution",
      organization: "Community Food Bank",
      description: "Help sort and distribute food to families in need.",
      category: "Community Service",
      commitment: "4 hours/week",
      distance: 1.5,
      latitude: 40.7328,
      longitude: -74.0060,
      image: "/images/food-bank.jpg",
      date: "2025-02-15T09:00:00Z", // Saturday morning
      time: "9:00 AM",
      day: "Saturday",
      recurring: true,
      spots_available: 8,
    },
    {
      id: 5,
      title: "Youth Mentoring Program",
      organization: "Youth Empowerment Center",
      description: "Mentor young people in academic and life skills.",
      category: "Education",
      commitment: "2 hours/week",
      distance: 3.0,
      latitude: 40.7428,
      longitude: -73.9911,
      image: "/images/youth-mentor.jpg",
      date: "2025-02-11T16:30:00Z", // Tuesday afternoon
      time: "4:30 PM",
      day: "Tuesday",
      recurring: true,
      spots_available: 4,
    },
    {
      id: 6,
      title: "Animal Shelter Care",
      organization: "City Animal Rescue",
      description: "Help care for rescued animals and assist with shelter operations.",
      category: "Animal Welfare",
      commitment: "3 hours/week",
      distance: 2.2,
      latitude: 40.7489,
      longitude: -73.9680,
      image: "/images/animal-shelter.jpg",
      date: "2025-02-09T11:00:00Z", // Sunday morning
      time: "11:00 AM",
      day: "Sunday",
      recurring: true,
      spots_available: 6,
    }
  ]
}

